### ISSUE TITLE
Contest mode

### ISSUE THREAD

**Issue by jlndk** [Duckapple/Kat#21]
To enter a contest:
`kat contest enter <contest-id>`
this makes future commands work against the contest url.

when contest is done and you want to go back to normal mode:
`kat contest leave` (perhaps with alias end)

**Comment by Duckapple** [comment]
Track which contest problems are solved in?
We need metadata for the funsies.

**Comment by Duckapple** [comment]
It is important to make this compatible with the itu kattis sessions, which work much the same but use a different namespace for their endpoints
