### ISSUE TITLE
Add continuous Kattis mode

### ISSUE THREAD

**Issue by Jakobis** [Duckapple/Kat#29]
Add the ability to enter a focused kattis mode where you can skip unnecessary command words.

Example of how it might work:
User inputs "kattis workmode easiest unsolved" which starts workmode on the list of unsolved problems starting with easiest. If the first problem on the list is problemx the program automatically runs "kattis get problemx" and then "kattis read problemx" (potentially with -o.

When the user is ready to test, they write "test" and the CLI runs "kattis test problemx"

When the user is ready to submit, they write "submit" and the CLI runs "kattis submit problemx -a" and if successful, archives and then repeats the process for the next problem in the list.

Ideally also includes the ability to skip a problem

**Comment by jlndk** [comment]
petition to name the command `work` instead of `workmode` has been accepted in chat
