### ISSUE TITLE
Add alternative to manually changing language

### ISSUE THREAD

**Issue by Jakobis** [Duckapple/Kat#43]
I have seperate folders that I use for Kattis written in Python, F# or Java. I would like to have the option to tell Kat what language the folder is for, and then just have that determine what language should be used

**Comment by Duckapple** [comment]
I am pretty certain that the way we load configurations would make it possible to do this already, by just including an overriding .kattisrc in the folder containing the problems with the specific language.

I am not closing, though, as a guide for this would be necessary.

**Comment by Duckapple** [comment]
Added a [guide in the Wiki tab](https://github.com/Duckapple/Kat/wiki/Multiple-configuration-files)
