### ISSUE TITLE
Add flag to "test" command for automatically submitting if it passes tests

### ISSUE THREAD

**Issue by CptF1nn** [Duckapple/Kat#47]
Sometimes, you're so sure of your code that you want to run kattis test and immediately submit the code if it passes the tests.

I imagine it could look something like this:
`kattis test -s problemname`

And to circumvent the y/N on kattis submit, you could even have a force submit with:
`kattis test -fs problemname`

This might all be compressed into a single command (test-submit) instead of flags:
`kattis ts problemname`

**Comment by Duckapple** [comment]
This is possible (at least it is now, don't know if it worked before)
