### ISSUE TITLE
Test specific index case only

### ISSUE THREAD

**Issue by CptF1nn** [Duckapple/Kat#48]
If for example a problem has many test cases
[baiscprogramming1](https://open.kattis.com/problems/basicprogramming1) for example has a lot that take some time to go through.

Testing the last sample with ``kattis test basicprogramming1 7`` would make it  immensely faster.

This could even include testing only a range, 5-7 on basicprogramming1 for example.

**Comment by CptF1nn** [comment]
Working on a PR for this currently:
![image](https://user-images.githubusercontent.com/12821408/98817309-3ae14400-242a-11eb-9aef-5109463c8bee.png)

So far ranges, single index and multiple indices work, but I have broken the way to test another file than the problem name file.

**Comment by Duckapple** [comment]
Closed by 3615aa56a2e8fe0a7cec077baf8a6a793a64392c
